#!/bin/bash
# ussage . ./CompileandExport NameOfFileToExecute
nameOfFile=$1
nameOfFile="${nameOfFile%%.*}"

unset LD_PRELOAD

gcc -shared -fPIC -o $nameOfFile.so $nameOfFile.c -ldl

export LD_PRELOAD=./$nameOfFile.so
